-- Script DDL compatível com MySQL 8+ (ajuste tipos se usar outro SGBD)

SET FOREIGN_KEY_CHECKS = 0;

CREATE DATABASE IF NOT EXISTS intellimarket CHARACTER SET = 'utf8mb4' COLLATE = 'utf8mb4_unicode_ci';
USE intellimarket;

-- tabela usuario
CREATE TABLE IF NOT EXISTS usuario (
  AUTOID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(120) NOT NULL,
  USERNAME VARCHAR(50) NOT NULL UNIQUE,
  EMAIL VARCHAR(150) NOT NULL UNIQUE,
  SENHA_HASH VARCHAR(255) NOT NULL,
  ROLE VARCHAR(20) NOT NULL DEFAULT 'CLIENT',
  TELEFONE VARCHAR(30),
  AVATAR_URL VARCHAR(512),
  ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CHECK (ROLE IN ('ADMIN','STAFF','CLIENT'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- tabela setor
CREATE TABLE IF NOT EXISTS setor (
  AUTOID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(120) NOT NULL,
  CODIGO VARCHAR(60) UNIQUE,
  DESCRICAO VARCHAR(255),
  LOCALIZACAO VARCHAR(120),
  ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- adiciona dados de exemplo na tabela setor
INSERT IGNORE INTO setor (AUTOID, NOME, CODIGO, DESCRICAO, LOCALIZACAO, ATIVO) VALUES
  (1, 'Mercearia', 'SET-MER', 'Produtos de mercearia e não perecíveis', 'Corredor A', TRUE),
  (2, 'Hortifruti', 'SET-HORT', 'Frutas, verduras e legumes frescos', 'Corredor B', TRUE),
  (3, 'Bebidas',  'SET-BEB', 'Bebidas alcoólicas e não alcoólicas', 'Corredor C', TRUE),
  (4, 'Padaria',  'SET-PAD', 'Pães, bolos e itens de panificação', 'Corredor D', TRUE);

-- tabela produto
CREATE TABLE IF NOT EXISTS produto (
  AUTOID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(200) NOT NULL,
  DESCRICAO VARCHAR(1000),
  VALOR DECIMAL(12,2) NOT NULL,
  QUANTIDADE INT NOT NULL,
  UNIDADE VARCHAR(32),
  CODIGO_BARRAS VARCHAR(128) UNIQUE,
  IMAGE_URL VARCHAR(512),
  ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  SETOR_ID BIGINT NOT NULL,
  CONSTRAINT fk_produto_setor FOREIGN KEY (SETOR_ID) REFERENCES setor(AUTOID) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- adiciona dados de exemplo na tabela produto (referenciando SETOR_ID acima)
INSERT IGNORE INTO produto (NOME, DESCRICAO, VALOR, QUANTIDADE, UNIDADE, CODIGO_BARRAS, IMAGE_URL, ATIVO, SETOR_ID) VALUES
  ('Arroz Branco 5kg',       'Arroz branco tipo 1',         19.90, 50,  'UN',  '7891000000017', NULL, TRUE, 1),
  ('Feijão Carioca 1kg',     'Feijão carioca tradicional',   6.50, 100, 'UN',  '7891000000024', NULL, TRUE, 1),
  ('Banana Prata 1kg',       'Banana prata fresca',          4.20, 200, 'KG',  '7891000000031', NULL, TRUE, 2),
  ('Alface Crespa',          'Alface crespa 1 unidade',      2.50, 80,  'UN',  '7891000000048', NULL, TRUE, 2),
  ('Coca-Cola 2L',           'Refrigerante cola 2 litros',   7.99, 120, 'UN',  '7891000000055', NULL, TRUE, 3),
  ('Cerveja Pilsen 350ml',   'Cerveja Pilsen lata 350ml',    3.50, 300, 'UN',  '7891000000062', NULL, TRUE, 3),
  ('Pão Francês 10un',       'Pacote com 10 pães franceses', 5.00, 60,  'PAC', '7891000000079', NULL, TRUE, 4),
  ('Bolo de Chocolate 500g', 'Bolo confeitado 500g',        15.00, 20,  'UN',  '7891000000086', NULL, TRUE, 4);

-- tabela venda
CREATE TABLE IF NOT EXISTS venda (
  AUTOID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  DATA DATETIME NOT NULL,
  TOTAL DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  USUARIO_ID BIGINT NOT NULL,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  PAYMENT_METHOD VARCHAR(255),
  CREATED_AT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_venda_usuario FOREIGN KEY (USUARIO_ID) REFERENCES usuario(AUTOID) ON DELETE RESTRICT ON UPDATE CASCADE,
  CHECK (STATUS IN ('PENDING','PAID','CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- tabela item_venda
CREATE TABLE IF NOT EXISTS item_venda (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  QUANTIDADE INT NOT NULL,
  PRECO_UNITARIO DECIMAL(12,2) NOT NULL,
  VENDA_ID BIGINT NOT NULL,
  PRODUTO_ID BIGINT NOT NULL,
  CREATED_AT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  DESCONTO DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  TAXA DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  OBSERVACAO VARCHAR(1000),
  PRODUTO_NOME_SNAPSHOT VARCHAR(200),
  PRODUTO_BARRA_SNAPSHOT VARCHAR(128),
  CONSTRAINT fk_itemvenda_venda FOREIGN KEY (VENDA_ID) REFERENCES venda(AUTOID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_itemvenda_produto FOREIGN KEY (PRODUTO_ID) REFERENCES produto(AUTOID) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- índices úteis
CREATE INDEX idx_produto_setor ON produto(SETOR_ID);
CREATE INDEX idx_venda_usuario ON venda(USUARIO_ID);
CREATE INDEX idx_itemvenda_venda ON item_venda(VENDA_ID);
CREATE INDEX idx_itemvenda_produto ON item_venda(PRODUTO_ID);

SET FOREIGN_KEY_CHECKS = 1;
